angular.module("tab", [])
    .directive("tab",function($http){
        return {
            restrict:"A",
            templateUrl:"tpl/tab.html",
            replace:true,
            scope:{
              width:"@",
              height:"@",
              titleh:"@",
              border:"@"
            },
            link:function($scope){
                alert($http)
                $scope.arr=[
                    {title:"第一选项",con:"12321312"},
                    {title:"第二选项",con:"222343222"},
                    {title:"第三选项",con:"333432433"},
                    {title:"第四选项",con:"444432444"},
                    {title:"第五选项",con:"444432444"}
                ];
                $scope.currentid=0;
                $scope.show=function(id){
                    $scope.currentid=id;
                }
                $scope.len=100/$scope.arr.length+"%";
            }
        }
    })